filter:
    excluded_paths:
        - examples/*
        - tests/*
        - src/Schemas/*
build:
    nodes:
        analysis:
            project_setup:
                override: true
            tests:
                override: php-scrutinizer-run
